name: Android CI

on:
  push

jobs:
  build_release:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Retrieve version
        run: |
          echo VERSION=$(echo ${{ github.event.head_commit.id }} | head -c 10) >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-deps
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/build-cache-*
          key: gradle-builds-${{ github.sha }}
          restore-keys: gradle-builds
      - name: Build with Gradle
        run: |
          bash ./gradlew assembleRelease
      - name: Rename
        run: |
          echo APK_FILE=${{ github.workspace }}/app/build/outputs/apk/release/BilibiliHD2_release_${{ env.VERSION }}.apk >> $GITHUB_ENV
          mv ${{ github.workspace }}/app/build/outputs/apk/release/app-release.apk ${{ github.workspace }}/app/build/outputs/apk/release/BilibiliHD2_release_${{ env.VERSION }}.apk
      - name: Upload built apk
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: BilibiliHD2_release_${{ env.VERSION }}.apk
          path: ${{ env.APK_FILE }}
      - name: Upload mapping.txt to GitHub
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: mapping.txt
          path: ${{ github.workspace }}/app/build/outputs/mapping/release/mapping.txt


  build_debug:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Retrieve version
        run: |
          echo VERSION=$(echo ${{ github.event.head_commit.id }} | head -c 10) >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-deps
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/build-cache-*
          key: gradle-builds-${{ github.sha }}
          restore-keys: gradle-builds
      - name: Build with Gradle
        run: |
          bash ./gradlew assembleDebug
      - name: Upload built apk
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: BilibiliHD2_debug_${{ env.VERSION }}.apk
          path: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk
